[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 3002
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200